version: 2
updates:
- package-ecosystem: docker
  directory: "/docker/debian/nginx"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Melbourne
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/docker/debian/apache"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Melbourne
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/docker/alpine/nginx"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Melbourne
  open-pull-requests-limit: 10
- package-ecosystem: docker
  directory: "/docker/alpine/apache"
  schedule:
    interval: daily
    time: "08:00"
    timezone: Australia/Melbourne
  open-pull-requests-limit: 10
