version: "3.7"
services:
    www01:
        build: 
            context: .
            dockerfile: '.docker/Dockerfile'
            args: 
                ENVIRONMENT: development
        env_file: '.env'
        image: samhwang/php
        links:
            - db
            - mailhog
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
    db:
        env_file: '.env'
        image: mysql:8.0
        ports:
            - '3306:3306'
        restart: always
        volumes:
            - .docker/mysql/storage:/var/lib/mysql:cached
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        restart: always
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: always
    composer:
        image: composer
        command: install --no-interaction --no-plugins --no-scripts --prefer-dist --ignore-platform-reqs
        volumes: 
            - .:/app
