version: "3.7"
services:
    www01:
        build: 
            context: .
            dockerfile: '.docker/Dockerfile'
        env_file: '.env'
        image: samhwang/docker-php
        links:
            - db
            - mailhog
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - .:/var/www/html
    db:
        env_file: '.env'
        image: mysql:8.0
        ports:
            - '3306:3306'
        restart: always
        volumes:
            - .docker/mysql/storage:/var/lib/mysql:cached
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        restart: always
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8081:80"
        restart: always
    mailhog:
        image: mailhog/mailhog:latest
        ports:
            - "1025:1025"
            - "8025:8025"
        restart: always
